### ISSUE TITLE
XSS or CORS?

### ISSUE THREAD

**Issue by Lewiscowles1986** [openresty/xss-nginx-module#11]
Seems like it's a jsonp wrapper to facilitate CORS, not much to do with traditional XSS. Can you confirm please?

**Comment by agentzh** [comment]
@Lewiscowles1986 Read the document.

**Comment by agentzh** [comment]
@Lewiscowles1986 Yes, it is jsonp.

**Comment by Lewiscowles1986** [comment]
I Have read the document. This basically has less to do with XSS than specifically CORS workaround using JSONP. My point was that it contains neither CORS or JSONP in it's name. In any case, thank you for your time
